version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13p55ydqturm9"
s3_prefix = "sam-demo-app"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBUrl=\"''\" Environment=\"preproduction\" ProjectName=\"SamDemoApp\" ServiceName=\"Membership\""
